Align for develop version of thinking-runtime, enhance CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,8 +18,21 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
+      - name: Install develop versions of thinking requirements
+        if: ${{ github.ref != 'refs/heads/main' }}
+        run: |
+          bash ./install_develop.sh
+      - name: Install requirements
+        run: |
+          [ -f ./requirements.txt ] && pip install -r ./requirements.txt || echo "No requirements.txt found"
+          [ -f ./test-requirements.txt ] && pip install -r ./test-requirements.txt || echo "No test-requirements.txt found"
       - name: Run tests
         run: |
-          python -m pip install -r ./requirements.txt
           chmod +x ./all_tests.sh
           ./all_tests.sh
+          RESULT_CODE=$?
+          echo "Mind you that the tests for this package will report failures, as this is a testing framework and the"
+          echo "  suite covers what happens on test failure"
+          echo "The only accurate indicator of success is the result code of the script ($RESULT_CODE)."
+          echo "  Btw, if it wasn't 0, then this job would fail before printing this message"
+          
